export default {
  UNASSIGNABLE_FULL_COURSES: 1,
  UNASSIGNABLE_MIN_COURSE_REQUIREMENTS: 2,
  COURSE_LIST_NOT_VALID: 3,
  EMPTY_COURSE_LIST: 4,
  PEOPLE_LIST_NOT_VALID: 5,
  EMPTY_PEOPLE_LIST: 6,
  UNKNOWN_COURSE_IN_PRIORITIES: 7,
  NO_PRIORITIES_FOUND: 8,
  PRIORITY_HOLES: 9,
  DUPLICATED_PRIORITIES: 10,
  UNFILLED_PRIORITIES: 11
};
